import Foundation

enum AppLanguage: String, CaseIterable, Codable, Identifiable {
    case system
    case zhHans
    case en

    var id: String { rawValue }

    var label: String {
        switch self {
        case .system: "跟随系统 / System"
        case .zhHans: "中文"
        case .en: "English"
        }
    }

    var resolvedCode: String {
        switch self {
        case .zhHans:
            "zh"
        case .en:
            "en"
        case .system:
            Locale.preferredLanguages.first?.hasPrefix("zh") == true ? "zh" : "en"
        }
    }
}

enum L10n {
    static func t(_ key: String, _ language: AppLanguage) -> String {
        let table = language.resolvedCode == "zh" ? zh : en
        return table[key] ?? en[key] ?? key
    }

    private static let zh: [String: String] = [
        "app.name": "2K HiDPI 助手",
        "menu.displays": "显示器",
        "menu.refresh": "刷新显示器",
        "menu.openMain": "打开主窗口",
        "menu.moreModes": "更多推荐模式",
        "menu.quickSwitch": "快速切换分辨率",
        "menu.more": "更多",
        "nav.displays": "显示器",
        "empty.noDisplay": "没有显示器",
        "action.refresh": "刷新",
        "status.ready": "就绪",
        "status.localOnly": "显示模式未切换，已保持当前状态",
        "status.updated": "已切换",
        "display.builtin": "内建显示器",
        "display.external": "外接显示器",
        "display.fallbackName": "显示器",
        "display.all": "所有显示器",
        "display.sleep": "关闭所有显示器",
        "display.vendor": "厂商",
        "display.model": "型号",
        "display.serial": "序列号",
        "display.product": "产品名",
        "display.physicalSize": "物理尺寸",
        "display.estimatedPPI": "估算像素密度",
        "display.modes": "可用模式",
        "display.identifiers": "显示器 ID",
        "display.manufactured": "制造时间",
        "display.technicalDetails": "技术详情",
        "display.defaultResolution": "默认分辨率",
        "display.currentResolution": "当前分辨率",
        "display.refreshRate": "刷新率",
        "display.colorProfile": "颜色空间",
        "display.role": "显示器状态",
        "display.main": "主显示器",
        "display.active": "在线",
        "display.inactive": "未激活",
        "display.modeUnavailable": "当前显示模式不可用",
        "display.native": "检测到的原生模式",
        "display.class": "屏幕类型",
        "display.class.2k": "2K / QHD 显示器",
        "display.class.2_5k": "2.5K 显示器",
        "display.class.4k": "4K 或更高分辨率显示器",
        "display.class.low": "低于 2K 的显示器",
        "display.class.unknown": "未识别类型",
        "hidpi.title": "HiDPI 缩放",
        "hidpi.current": "当前模式",
        "hidpi.diagnosis": "诊断",
        "hidpi.available": "可用 HiDPI 模式",
        "hidpi.recommended": "推荐模式",
        "hidpi.best": "首选",
        "hidpi.noRecommendations": "没有可推荐的 HiDPI 模式",
        "hidpi.none": "当前系统没有暴露可切换的 HiDPI 模式",
        "hidpi.currentOn": "当前已经是 HiDPI",
        "hidpi.currentOff": "当前不是 HiDPI，字体可能偏糊或偏小",
        "hidpi.apply": "应用",
        "hidpi.confirm": "保留这个模式",
        "hidpi.rollback": "恢复之前模式",
        "hidpi.pending": "如果不确认，将自动恢复之前模式",
        "hidpi.confirmed": "已保留当前 HiDPI 模式",
        "hidpi.openSettings": "打开系统显示设置",
        "hidpi.note": "2K/2.5K 显示器是否能 HiDPI，取决于 macOS 是否暴露对应缩放模式。这里会列出系统当前允许切换的真实模式。",
        "hidpi.modeAvailabilityNote": "如果 1920 x 1080 只显示 1x，说明 macOS 当前没有为这台屏幕暴露 1920 x 1080 HiDPI；本工具只切换系统已经允许的真实模式。",
        "hidpi.unavailableTargets": "推荐但系统未暴露",
        "hidpi.notExposed": "未暴露",
        "hidpi.standard": "标准",
        "systemSettings.title": "系统显示设置",
        "systemSettings.resolutions": "缩放分辨率",
        "systemSettings.default": "默认",
        "systemSettings.current": "当前",
        "settings.language": "语言",
        "settings.title": "设置",
        "settings.appLanguage": "应用语言",
        "settingsPane.displays": "显示器",
        "settingsPane.general": "通用",
        "settingsPane.presets": "预设",
        "settingsPane.schedules": "计划任务",
        "settingsPane.brightnessVolumeKeys": "亮度与音量键",
        "settingsPane.globalShortcuts": "全局快捷键",
        "settingsPane.customShortcuts": "自定义快捷键",
        "settingsPane.commandLineAI": "命令行与 AI",
        "settingsPane.about": "关于",
        "preset.title": "预设",
        "preset.saveCurrent": "保存当前显示器配置",
        "darkMode.on": "深色模式",
        "darkMode.off": "深色模式",
        "nightShift.on": "夜览开启",
        "nightShift.off": "夜览关闭",
        "sync.on": "联动开启",
        "sync.off": "联动关闭",
        "sync.follow": "跟随显示器",
        "sync.followOff": "不跟随",
        "controlMode.title": "控制模式",
        "controlMode.software": "当前使用软件控制模式",
        "controlMode.whatIsThis": "这些是什么意思？",
        "controlMode.m1HDMI": "DDC 在 M1 Mac 的 HDMI 上无法工作",
        "inputSource.title": "输入源",
        "inputSource.experimentalWarning": "实验性功能：可能会导致显示器变砖",
        "power.on": "开启",
        "power.off": "关闭",
        "error.modeUnavailable": "显示模式不再可用",
        "error.configBegin": "无法开始显示配置",
        "error.configMode": "无法配置显示模式",
        "error.configApply": "无法应用显示模式"
    ]

    private static let en: [String: String] = [
        "app.name": "2K HiDPI Assistant",
        "menu.displays": "Displays",
        "menu.refresh": "Refresh Displays",
        "menu.openMain": "Open Main Window",
        "menu.moreModes": "More recommended modes",
        "menu.quickSwitch": "Quick switch resolution",
        "menu.more": "More",
        "nav.displays": "Displays",
        "empty.noDisplay": "No Display",
        "action.refresh": "Refresh",
        "status.ready": "Ready",
        "status.localOnly": "Display mode did not change; current state was preserved",
        "status.updated": "Switched",
        "display.builtin": "Built-in Display",
        "display.external": "External Display",
        "display.fallbackName": "Display",
        "display.all": "All Displays",
        "display.sleep": "Sleep all displays",
        "display.vendor": "Vendor",
        "display.model": "Model",
        "display.serial": "Serial",
        "display.product": "Product",
        "display.physicalSize": "Physical size",
        "display.estimatedPPI": "Estimated density",
        "display.modes": "Available modes",
        "display.identifiers": "Display IDs",
        "display.manufactured": "Manufactured",
        "display.technicalDetails": "Technical details",
        "display.defaultResolution": "Default resolution",
        "display.currentResolution": "Current resolution",
        "display.refreshRate": "Refresh rate",
        "display.colorProfile": "Color space",
        "display.role": "Display status",
        "display.main": "Main display",
        "display.active": "Online",
        "display.inactive": "Inactive",
        "display.modeUnavailable": "Current mode unavailable",
        "display.native": "Detected native mode",
        "display.class": "Display class",
        "display.class.2k": "2K / QHD display",
        "display.class.2_5k": "2.5K display",
        "display.class.4k": "4K or higher display",
        "display.class.low": "Below 2K display",
        "display.class.unknown": "Unknown display class",
        "hidpi.title": "HiDPI Scaling",
        "hidpi.current": "Current mode",
        "hidpi.diagnosis": "Diagnosis",
        "hidpi.available": "Available HiDPI modes",
        "hidpi.recommended": "Recommended modes",
        "hidpi.best": "Best pick",
        "hidpi.noRecommendations": "No recommended HiDPI modes",
        "hidpi.none": "macOS is not exposing switchable HiDPI modes for this display",
        "hidpi.currentOn": "Current mode is already HiDPI",
        "hidpi.currentOff": "Current mode is not HiDPI; text may be blurry or too small",
        "hidpi.apply": "Apply",
        "hidpi.confirm": "Keep This Mode",
        "hidpi.rollback": "Revert",
        "hidpi.pending": "If you do not confirm, the previous mode will be restored automatically",
        "hidpi.confirmed": "Current HiDPI mode kept",
        "hidpi.openSettings": "Open Display Settings",
        "hidpi.note": "HiDPI on a 2K/2.5K display depends on whether macOS exposes matching scaled modes. This list only shows real modes the system currently allows.",
        "hidpi.modeAvailabilityNote": "If 1920 x 1080 only appears as 1x, macOS is not currently exposing a 1920 x 1080 HiDPI mode for this display. This app only switches real modes the system already allows.",
        "hidpi.unavailableTargets": "Recommended but not exposed",
        "hidpi.notExposed": "Not exposed",
        "hidpi.standard": "Standard",
        "systemSettings.title": "System Display Settings",
        "systemSettings.resolutions": "Scaled resolutions",
        "systemSettings.default": "Default",
        "systemSettings.current": "Current",
        "settings.language": "Language",
        "settings.title": "Settings",
        "settings.appLanguage": "App language",
        "settingsPane.displays": "Displays",
        "settingsPane.general": "General",
        "settingsPane.presets": "Presets",
        "settingsPane.schedules": "Schedules",
        "settingsPane.brightnessVolumeKeys": "Brightness & Volume Keys",
        "settingsPane.globalShortcuts": "Global Keyboard Shortcuts",
        "settingsPane.customShortcuts": "Custom Keyboard Shortcuts",
        "settingsPane.commandLineAI": "Command Line & AI",
        "settingsPane.about": "About",
        "preset.title": "Presets",
        "preset.saveCurrent": "Save current display setup",
        "darkMode.on": "Dark Mode",
        "darkMode.off": "Dark Mode",
        "nightShift.on": "Night Shift On",
        "nightShift.off": "Night Shift Off",
        "sync.on": "Sync On",
        "sync.off": "Sync Off",
        "sync.follow": "Follow Display",
        "sync.followOff": "Do Not Follow",
        "controlMode.title": "Control Mode",
        "controlMode.software": "Using software control mode",
        "controlMode.whatIsThis": "What do these mean?",
        "controlMode.m1HDMI": "DDC does not work over HDMI on M1 Macs",
        "inputSource.title": "Input Source",
        "inputSource.experimentalWarning": "Experimental: may lock up the monitor",
        "power.on": "On",
        "power.off": "Off",
        "error.modeUnavailable": "Display mode is no longer available",
        "error.configBegin": "Could not begin display configuration",
        "error.configMode": "Could not configure display mode",
        "error.configApply": "Could not apply display mode"
    ]
}
