import Foundation

enum AppLanguage: String, CaseIterable, Codable, Identifiable {
    case system
    case zhHans
    case en

    var id: String { rawValue }

    var label: String {
        switch self {
        case .system: "跟随系统 / System"
        case .zhHans: "中文"
        case .en: "English"
        }
    }

    var resolvedCode: String {
        switch self {
        case .zhHans:
            "zh"
        case .en:
            "en"
        case .system:
            Locale.preferredLanguages.first?.hasPrefix("zh") == true ? "zh" : "en"
        }
    }
}

enum L10n {
    static func t(_ key: String, _ language: AppLanguage) -> String {
        let table = language.resolvedCode == "zh" ? zh : en
        return table[key] ?? en[key] ?? key
    }

    private static let zh: [String: String] = [
        "app.name": "2K HiDPI 助手",
        "menu.displays": "显示器",
        "menu.refresh": "刷新显示器",
        "menu.openMain": "打开主窗口",
        "menu.quit": "退出",
        "menu.moreModes": "更多推荐模式",
        "menu.quickSwitch": "快速切换分辨率",
        "menu.more": "更多",
        "nav.displays": "显示器",
        "empty.noDisplay": "没有显示器",
        "action.refresh": "刷新",
        "status.ready": "就绪",
        "status.localOnly": "显示模式未切换，已保持当前状态",
        "status.updated": "已切换",
        "display.builtin": "内建显示器",
        "display.external": "外接显示器",
        "display.fallbackName": "显示器",
        "display.vendor": "厂商",
        "display.model": "型号",
        "display.serial": "序列号",
        "display.product": "产品名",
        "display.physicalSize": "物理尺寸",
        "display.estimatedPPI": "估算像素密度",
        "display.modes": "可用模式",
        "display.identifiers": "显示器 ID",
        "display.manufactured": "制造时间",
        "display.technicalDetails": "技术详情",
        "display.defaultResolution": "默认分辨率",
        "display.currentResolution": "当前分辨率",
        "display.refreshRate": "刷新率",
        "display.colorProfile": "颜色空间",
        "display.role": "显示器状态",
        "display.main": "主显示器",
        "display.active": "在线",
        "display.inactive": "未激活",
        "display.modeUnavailable": "当前显示模式不可用",
        "display.native": "检测到的原生模式",
        "display.class": "屏幕类型",
        "display.class.2k": "2K / QHD 显示器",
        "display.class.2_5k": "2.5K 显示器",
        "display.class.4k": "4K 或更高分辨率显示器",
        "display.class.low": "低于 2K 的显示器",
        "display.class.unknown": "未识别类型",
        "hidpi.title": "HiDPI 缩放",
        "hidpi.current": "当前模式",
        "hidpi.diagnosis": "诊断",
        "hidpi.available": "可用 HiDPI 模式",
        "hidpi.recommended": "推荐模式",
        "hidpi.best": "首选",
        "hidpi.noRecommendations": "没有可推荐的 HiDPI 模式",
        "hidpi.none": "当前系统没有暴露可切换的 HiDPI 模式",
        "hidpi.currentOn": "当前已经是 HiDPI",
        "hidpi.currentOff": "当前不是 HiDPI，字体可能偏糊或偏小",
        "hidpi.apply": "应用",
        "hidpi.confirm": "保留这个模式",
        "hidpi.rollback": "恢复之前模式",
        "hidpi.pending": "如果不确认，将自动恢复之前模式",
        "hidpi.confirmed": "已保留当前 HiDPI 模式",
        "hidpi.openSettings": "打开系统显示设置",
        "hidpi.note": "此列表只显示 macOS 当前允许切换的 HiDPI 模式。安装自定义缩放配置不代表系统已支持该模式。",
        "hidpi.modeAvailabilityNote": "系统未列出的分辨率不能直接切换。可先检查是否支持自定义缩放配置，再重新连接屏幕或重启后刷新。",
        "hidpi.unavailableTargets": "推荐但系统未暴露",
        "hidpi.notExposed": "未暴露",
        "hidpi.standard": "标准",
        "virtual.warning": "实验性：使用 macOS 私有 API 创建虚拟显示器并镜像到此屏幕，不会让系统支持更多显示模式。可能降低刷新率并使文字偏软；仅在本应用运行期间有效，退出时恢复，不会自动重建。",
        "physical.enableMore": "启用更多 HiDPI",
        "physical.installed": "配置已安装，可先关开屏幕电源后刷新；未生效再重新连接或重启。",
        "physical.available": "%@ HiDPI 已可选",
        "physical.restored": "原配置已恢复，可先关开屏幕电源后刷新；当前分辨率不会立即改变。",
        "physical.conflict": "配置或备份存在冲突，无法安全恢复原配置。",
        "physical.restore": "恢复原配置",
        "physical.title.install": "安装 HiDPI 缩放配置？",
        "physical.title.restore": "恢复原显示配置？",
        "physical.target": "目标分辨率",
        "physical.resolution": "%@ · HiDPI",
        "physical.vendorID": "Vendor ID（厂商）",
        "physical.productID": "Product ID（型号）",
        "physical.matchingModels": "此配置按 Vendor/Product ID 匹配型号，会影响同一 VID/PID 的屏幕，而不只是此屏幕。目前连接的匹配屏幕：%d 台。",
        "physical.authorization": "确认后需要管理员授权，才会更改系统显示器配置。取消不会写入配置。",
        "physical.installWarning": "安装只添加自定义缩放配置，不会立即切换分辨率。请重新连接屏幕或重启后刷新；macOS 仍可能不支持此 HiDPI 模式。只有系统列出该模式后才能试用，显示效果仍需确认。",
        "physical.restoreWarning": "将精确恢复安装前的原配置；如果安装前没有配置文件，则移除本次安装的文件。请重新连接屏幕或重启后刷新，系统不会立即更新显示模式。",
        "physical.notFirmware": "只更改 macOS 显示器缩放配置，不修改屏幕固件。",
        "physical.cancel": "取消",
        "physical.confirm.install": "授权并安装",
        "physical.confirm.restore": "授权并恢复",
        "physical.changing": "正在等待授权或写入配置…",
        "physical.errorUnavailable": "屏幕或分辨率条件已改变，请刷新后重试",
        "physical.modeNotApplied": "系统没有实际切换到所选模式，已恢复",
        "virtual.compatibility": "实验性兼容方案",
        "virtual.chooseTarget": "试用镜像缩放分辨率",
        "virtual.none": "此屏幕没有可试用的镜像缩放分辨率",
        "systemSettings.title": "系统显示设置",
        "systemSettings.resolutions": "缩放分辨率",
        "systemSettings.default": "默认",
        "systemSettings.current": "当前",
        "settings.language": "语言",
        "settings.title": "分辨率工具",
        "settings.appLanguage": "应用语言",
        "preset.title": "分辨率预设",
        "preset.saveCurrent": "保存当前分辨率",
        "preset.name": "预设名称",
        "preset.empty": "尚无分辨率预设",
        "preset.delete": "删除",
        "preset.note": "只保存物理显示器的分辨率与刷新率；虚拟 HiDPI 会话不会保存或自动恢复。",
        "ui.confirmationNote": "15 秒确认，未确认自动恢复",
        "ui.resolution": "分辨率",
        "ui.screen": "屏幕",
        "ui.hiDPIResolution": "HiDPI 分辨率",
        "ui.chooseResolution": "选择分辨率",
        "ui.advanced": "高级详情",
        "ui.moreModes": "全部系统模式",
        "ui.notHiDPI": "HiDPI 未开启",
        "ui.changing": "正在切换分辨率…",
        "ui.keepQuestion": "是否保留此分辨率？",
        "ui.keep": "保留分辨率",
        "ui.restore": "恢复原设置",
        "ui.kept": "已保留分辨率",
        "ui.restored": "已恢复原设置",
        "ui.scalingRisk": "此模式可能降低刷新率或使文字略软；退出应用时恢复原设置。",
        "error.restorePending": "macOS 尚未完成原屏幕恢复，请稍后重试。",
        "error.modeUnavailable": "显示模式不再可用",
        "error.configBegin": "无法开始显示配置",
        "error.configMode": "无法配置显示模式",
        "error.configApply": "无法应用显示模式"
    ]

    private static let en: [String: String] = [
        "app.name": "2K HiDPI Assistant",
        "menu.displays": "Displays",
        "menu.refresh": "Refresh Displays",
        "menu.openMain": "Open Main Window",
        "menu.quit": "Quit",
        "menu.moreModes": "More recommended modes",
        "menu.quickSwitch": "Quick switch resolution",
        "menu.more": "More",
        "nav.displays": "Displays",
        "empty.noDisplay": "No Display",
        "action.refresh": "Refresh",
        "status.ready": "Ready",
        "status.localOnly": "Display mode did not change; current state was preserved",
        "status.updated": "Switched",
        "display.builtin": "Built-in Display",
        "display.external": "External Display",
        "display.fallbackName": "Display",
        "display.vendor": "Vendor",
        "display.model": "Model",
        "display.serial": "Serial",
        "display.product": "Product",
        "display.physicalSize": "Physical size",
        "display.estimatedPPI": "Estimated density",
        "display.modes": "Available modes",
        "display.identifiers": "Display IDs",
        "display.manufactured": "Manufactured",
        "display.technicalDetails": "Technical details",
        "display.defaultResolution": "Default resolution",
        "display.currentResolution": "Current resolution",
        "display.refreshRate": "Refresh rate",
        "display.colorProfile": "Color space",
        "display.role": "Display status",
        "display.main": "Main display",
        "display.active": "Online",
        "display.inactive": "Inactive",
        "display.modeUnavailable": "Current mode unavailable",
        "display.native": "Detected native mode",
        "display.class": "Display class",
        "display.class.2k": "2K / QHD display",
        "display.class.2_5k": "2.5K display",
        "display.class.4k": "4K or higher display",
        "display.class.low": "Below 2K display",
        "display.class.unknown": "Unknown display class",
        "hidpi.title": "HiDPI Scaling",
        "hidpi.current": "Current mode",
        "hidpi.diagnosis": "Diagnosis",
        "hidpi.available": "Available HiDPI modes",
        "hidpi.recommended": "Recommended modes",
        "hidpi.best": "Best pick",
        "hidpi.noRecommendations": "No recommended HiDPI modes",
        "hidpi.none": "macOS is not exposing switchable HiDPI modes for this display",
        "hidpi.currentOn": "Current mode is already HiDPI",
        "hidpi.currentOff": "Current mode is not HiDPI; text may be blurry or too small",
        "hidpi.apply": "Apply",
        "hidpi.confirm": "Keep This Mode",
        "hidpi.rollback": "Revert",
        "hidpi.pending": "If you do not confirm, the previous mode will be restored automatically",
        "hidpi.confirmed": "Current HiDPI mode kept",
        "hidpi.openSettings": "Open Display Settings",
        "hidpi.note": "This list only shows HiDPI modes macOS currently allows. Installing a custom scaling configuration does not mean the system supports that mode.",
        "hidpi.modeAvailabilityNote": "Resolutions not listed by macOS cannot be switched directly. Check eligibility for a custom scaling configuration, then reconnect the display or restart and refresh.",
        "hidpi.unavailableTargets": "Recommended but not exposed",
        "hidpi.notExposed": "Not exposed",
        "hidpi.standard": "Standard",
        "virtual.warning": "Experimental: creates a virtual display using a private macOS API and mirrors it to this screen. It does not make more system modes available. Refresh rate may decrease and text may soften. Lasts only while this app runs, restores on quit, and never restarts automatically.",
        "physical.enableMore": "Enable More HiDPI",
        "physical.installed": "Configuration installed. Try powering the display off/on, then refresh; reconnect or restart if needed.",
        "physical.available": "%@ HiDPI is selectable",
        "physical.restored": "Original configuration restored. Try powering the display off/on, then refresh. The current resolution does not change immediately.",
        "physical.conflict": "The configuration or backup conflicts with the saved state. Safe restoration is unavailable.",
        "physical.restore": "Restore Original Configuration",
        "physical.title.install": "Install HiDPI Scaling Configuration?",
        "physical.title.restore": "Restore Original Display Configuration?",
        "physical.target": "Target resolution",
        "physical.resolution": "%@ · HiDPI",
        "physical.vendorID": "Vendor ID",
        "physical.productID": "Product ID",
        "physical.matchingModels": "This configuration matches the model by Vendor/Product ID and affects displays sharing the same VID/PID, not just this display. Connected matching displays: %d.",
        "physical.authorization": "Administrator authorization is required after confirmation to change the system display configuration. Canceling writes nothing.",
        "physical.installWarning": "Installation only adds a custom scaling configuration; it does not switch resolutions immediately. Reconnect the display or restart, then refresh. macOS may still not support this HiDPI mode. Try it only after macOS lists the mode, and verify its visual quality.",
        "physical.restoreWarning": "The exact pre-installation configuration will be restored. If no configuration file existed before installation, the installed file will be removed. Reconnect the display or restart, then refresh; display modes do not update immediately.",
        "physical.notFirmware": "Only the macOS display scaling configuration changes. Display firmware is not modified.",
        "physical.cancel": "Cancel",
        "physical.confirm.install": "Authorize and Install",
        "physical.confirm.restore": "Authorize and Restore",
        "physical.changing": "Waiting for authorization or writing configuration…",
        "physical.errorUnavailable": "Display or resolution conditions changed. Refresh and try again.",
        "physical.modeNotApplied": "The requested mode was not applied; restored the previous mode.",
        "virtual.compatibility": "Experimental Compatibility",
        "virtual.chooseTarget": "Try Mirrored Scaling Resolution",
        "virtual.none": "No experimental mirrored scaling resolutions are available for this display",
        "systemSettings.title": "System Display Settings",
        "systemSettings.resolutions": "Scaled resolutions",
        "systemSettings.default": "Default",
        "systemSettings.current": "Current",
        "settings.language": "Language",
        "settings.title": "Resolution Tool",
        "settings.appLanguage": "App language",
        "preset.title": "Resolution Presets",
        "preset.saveCurrent": "Save Current Resolutions",
        "preset.name": "Preset name",
        "preset.empty": "No resolution presets yet",
        "preset.delete": "Delete",
        "preset.note": "Saves only physical display resolutions and refresh rates. Virtual HiDPI sessions are never saved or restored automatically.",
        "ui.confirmationNote": "Confirm within 15 seconds or revert",
        "ui.resolution": "Resolution",
        "ui.screen": "Screen",
        "ui.hiDPIResolution": "HiDPI Resolution",
        "ui.chooseResolution": "Choose Resolution",
        "ui.advanced": "Advanced Details",
        "ui.moreModes": "All System Modes",
        "ui.notHiDPI": "HiDPI is off",
        "ui.changing": "Switching resolution…",
        "ui.keepQuestion": "Keep this resolution?",
        "ui.keep": "Keep Resolution",
        "ui.restore": "Restore Previous Settings",
        "ui.kept": "Resolution kept",
        "ui.restored": "Previous settings restored",
        "ui.scalingRisk": "This mode may lower refresh rate or soften text. Previous settings restore on app quit.",
        "error.restorePending": "macOS has not finished restoring the physical display. Try again shortly.",
        "error.modeUnavailable": "Display mode is no longer available",
        "error.configBegin": "Could not begin display configuration",
        "error.configMode": "Could not configure display mode",
        "error.configApply": "Could not apply display mode"
    ]
}
